### ISSUE TITLE
Search does not return any results. Reroutes to 127.0.0.1:1313/?

### ISSUE THREAD

**Issue by pjarnhus** [vantagedesign/ace-documentation#38]
Hi,

Thank you for making an awesome Hugo theme. I have been using it for some time now and it is wonderful. I cannot, however, seem to get the search to work. Whenever I search for something, it basically reroutes to 127.0.0.1:1313/? and does not return any results.

I have just tried reinstalling the theme and get the same results. Checking the source of the generated HTML everything checks out with correct links to jQuery, popper, lunr and auto-complete. They are all available in a minified version for the generated site.

Is there some step that I am missing to get the search to work?

My config looks like this:
```toml
baseURL = "/"
languageCode = "en-uk"
title = "Zettelkasten"

# Set ace-documentation theme
theme = "ace-documentation"

# Set search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]
```
